#!/bin/bash
echo "=== НАСТРОЙКА GITHUB REPOSITORY ==="
echo ""
echo "Откройте в браузере: https://github.com/GeorgEvseyev/Prostor"
echo ""
echo "ШАГ 1: Branch Protection Rules"
echo "==============================="
echo "1. Settings → Branches → Add rule"
echo "2. Branch name pattern: main"
echo "3. Enable:"
echo "   ✓ Require a pull request before merging"
echo "   ✓ Require approvals (1)"
echo "   ✓ Require status checks to pass"
echo "   ✓ Require branches to be up to date before merging"
echo "4. Status checks:"
echo "   - CI - iOS Build and Test"
echo "5. Save changes"
echo ""
echo "ШАГ 2: Защита develop ветки"
echo "============================"
echo "1. Add rule"
echo "2. Branch name pattern: develop"
echo "3. Enable:"
echo "   ✓ Require status checks to pass"
echo "4. Status checks:"
echo "   - CI - iOS Build and Test"
echo "5. Save changes"
echo ""
echo "ШАГ 3: Environments"
echo "==================="
echo "1. Settings → Environments → New environment"
echo "2. Name: staging"
echo "3. Add secrets (если есть):"
echo "   - STAGING_API_URL"
echo "   - STAGING_KEYS"
echo "4. Create environment"
echo ""
echo "ШАГ 4: GitHub Actions Permissions"
echo "================================="
echo "1. Settings → Actions → General"
echo "2. Workflow permissions:"
echo "   ✓ Read and write permissions"
echo "3. Save"
echo ""
echo "ШАГ 5: Labels для Issues/PR"
echo "==========================="
echo "Создайте labels:"
echo "  - upgrade-available (цвет: 1D76DB)"
echo "  - automated (цвет: 0052CC)"
echo "  - priority: high (цвет: D93F0B)"
echo "  - priority: medium (цвет: FBCA04)"
echo "  - priority: low (цвет: 0E8A16)"
echo ""
echo "=== ГОТОВО ==="
echo "После настройки вернитесь в терминал"
